import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anonyme
 */
public class FicheClient extends javax.swing.JFrame {

    /**
     * Creates new form ReglementClient
     */
    public FicheClient() {
        initComponents();
        Actualiser(0);
    }
    
    public void Actualiser(int j) {
        DB.SelectNumClientDB();
        NumClient.removeAllItems();
        for(int i=0; i<DB.clients.size(); i++) {
            NumClient.addItem(DB.clients.get(i).getNum());
        }
        if(NumClient.getItemCount() !=0) {
        
            NumClient.setSelectedItem(DB.clients.get(j).getNum());
            NomClient.setText(DB.clients.get(j).getNomClient());
            Prenom.setText(DB.clients.get(j).getPrenom());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        fiche = new javax.swing.JTable();
        NumClient1 = new javax.swing.JLabel();
        NomClient1 = new javax.swing.JLabel();
        NomClient = new javax.swing.JTextField();
        PrenomClient1 = new javax.swing.JLabel();
        Prenom = new javax.swing.JTextField();
        NumClient = new javax.swing.JComboBox<>();
        Nouvelle1 = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fiche Client");

        fiche.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fiche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Pièce", "Date", "Débit", "Crédit", "Solde débitation", "Solde créditation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fiche.setToolTipText("");
        fiche.setCellSelectionEnabled(true);
        fiche.setRowHeight(30);
        jScrollPane2.setViewportView(fiche);

        NumClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumClient1.setText("N°Client :");

        NomClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NomClient1.setText("Nom :");

        NomClient.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        PrenomClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        PrenomClient1.setText("Prenom :");

        Prenom.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        NumClient.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumClientActionPerformed(evt);
            }
        });

        Nouvelle1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Nouvelle1.setText("New");
        Nouvelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nouvelle1ActionPerformed(evt);
            }
        });

        Supprimer.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Supprimer.setText("Delete");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Retour.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Retour.setText("Return ");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumClient1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumClient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NomClient1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrenomClient1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nouvelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Retour))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumClient1)
                    .addComponent(NomClient1)
                    .addComponent(NomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrenomClient1)
                    .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nouvelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Nouvelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nouvelle1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) fiche.getModel();
        model.addRow(new Object[6]);

    }//GEN-LAST:event_Nouvelle1ActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) fiche.getModel();
        int[] rows = fiche.getSelectedRows();
        for(int i=0;i<rows.length;i++)model.removeRow(rows[i]-i);
    }//GEN-LAST:event_SupprimerActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Interface I = new Interface();
        I.show();
        this.dispose();
    }//GEN-LAST:event_RetourActionPerformed

    private void NumClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumClientActionPerformed
        // TODO add your handling code here:
        int i=0;
        if (NumClient.getSelectedIndex()!= -1) {
            while (Integer.parseInt(DB.clients.get(i).getNum()) != Integer.parseInt(NumClient.getSelectedItem().toString())) i++;
            
            NomClient.setText(DB.clients.get(i).getNomClient());
            Prenom.setText(DB.clients.get(i).getPrenom());
        }
    }//GEN-LAST:event_NumClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReglementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReglementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReglementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReglementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReglementClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomClient;
    private javax.swing.JLabel NomClient1;
    private javax.swing.JButton Nouvelle1;
    public static javax.swing.JComboBox<String> NumClient;
    private javax.swing.JLabel NumClient1;
    private javax.swing.JTextField Prenom;
    private javax.swing.JLabel PrenomClient1;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTable fiche;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
